### ISSUE TITLE
Decide on version and deployment strategy for Jquery

### ISSUE THREAD

**Issue by nathan-rollins** [gios-asu/asu-web-standards-bootstrap4#2]
Jquery is a dependency of Bootstrap. Jquery < 3.4.0 contains moderate severity vulnerabilities. However, Drupal and WordPress both use old versions of Jquery. Jquery can be carefully upgraded to a more recent version, but this upgrade process runs the risk of backward-compatibility breaking issues with older plugins or themes.

GIOS has been successful running Jquery 2.4.x on WordPress for several years. Drupal Webspark installs a patch script that purportedly fixes the security vulnerability in Drupal's installed version of Jquery.

**Comment by SteveRyan-ASU** [comment]
The documentation for BS4 recommends using the [slim build for jQuery 3.4+](https://getbootstrap.com/docs/4.0/getting-started/introduction/#js). I'd say we should mirror this requirement in our own distribution.

slim jQuery vs regular jQuery
- Saves 6k worth of file size from the original
- Drops support of AJAX and some of the effects modules.

Is there any harm in relying on a CDN to "distribute" the code, vs including an actual downloaded version in the package?

Also, I'd say we should emphasize the latest version of jQuery here as a best practice. When we get around to building our next-gen WordPress and Drupal stuff, we can deal with the library inconsistencies within those distributions.

**Comment by nathan-rollins** [comment]
Actually, this is a non-issue. 

I have been exploring the [Bootstrap repository](https://github.com/twbs/bootstrap) to see how they manage various topics. The solution is to not bundle jQuery into our release package. We can either just instruct in our Readme that jQuery must be installed in any product using our UI Kit, or specify a specific version range required by this project in its "peerDependencies" settings in package.json. That will enable warnings if our project is imported without also installing a suitable version of jQuery.

This will allow any products that use the ASU Web Standards Bootstrap project to make their own decision on jQuery.

**Comment by nathan-rollins** [comment]
Closing this issue since the topic is effectively resolved.
