### ISSUE TITLE
Stories: Badges

### ISSUE THREAD

**Issue by nathan-rollins** [gios-asu/asu-web-standards-bootstrap4#25]
Implement:

* Stories that demonstrate feature
* Tests
* Copy Bootstrap Hugo Readme

**Comment by nathan-rollins** [comment]
Bootstrap docs: https://getbootstrap.com/docs/4.3/components/badge/

**Comment by bryanbarker** [comment]
https://github.com/gios-asu/asu-web-standards-bootstrap4/tree/brbarker-badges

**Comment by nathan-rollins** [comment]
PR Merged
