### ISSUE TITLE
Stories: Kitchen Sink for BS v4

### ISSUE THREAD

**Issue by SteveRyan-ASU** [gios-asu/asu-web-standards-bootstrap4#37]
Presumably, we are going to want to do some visual regression or unit testing against a "kitchen sink" page that is a classic case of the [Buddhist and the hot dog vendor](https://www.amazon.com/Enlightenment-Fathers-Day-Gift-Ideas/dp/B07QT9KSP8). 

A good reference for this new kitchen sink file is located here.
- https://github.com/csbarker/bootstrap-4-kitchen-sink

Will get to work. :-)

**Comment by nathan-rollins** [comment]
Oh, nice! Yeah, that is a great starting point.
