### ISSUE TITLE
Stories: Cards and card elements

### ISSUE THREAD

**Issue by bryanbarker** [gios-asu/asu-web-standards-bootstrap4#58]

**Comment by bryanbarker** [comment]
@nathan-rollins the Cards are ready for review, but I'm hoping to ask you about the JS for the Image placement within the bootstrap documentation: https://getbootstrap.com/docs/4.0/components/card/#images-1

Currently, our card documentation just has a static img placement. 
Can we discuss working towards making these images responsive (with dynamic sizing)?

**Comment by nathan-rollins** [comment]
Merged PR.

I forgot you had posted questions here. We can discuss and if we have changes to make, they can be pushed in a new PR.
